import type { MaintenanceService, ServiceDetail } from '@/lib/types'

/**
 * Online services offered through the automated business registration system.
 * Descriptions follow the wording of the current website. No eligibility rule,
 * fee amount or deadline is invented here — unavailable details are marked as
 * placeholders that an administrator must complete.
 */
const PLACEHOLDER_KM = '[ព័ត៌មានផ្លូវការត្រូវបញ្ចូល]'
const PLACEHOLDER_EN = '[Official information required]'

const FEE_NOTE_KM =
  'ថ្លៃសេវាត្រូវអនុវត្តតាមតារាងថ្លៃសេវាសាធារណៈផ្លូវការចុងក្រោយរបស់ក្រសួងពាណិជ្ជកម្ម។'
const FEE_NOTE_EN =
  'Fees are those set out in the latest official public service fee document of the Ministry of Commerce.'

export const services: ServiceDetail[] = [
  {
    slug: 'register-new-user',
    icon: 'user-plus',
    group: 'account',
    titleKm: 'ចុះឈ្មោះជាអ្នកប្រើប្រាស់ថ្មី',
    titleEn: 'Register a New User',
    summaryKm:
      'បង្កើតគណនីអ្នកប្រើប្រាស់ដើម្បីអាចប្រើប្រាស់សេវាកម្មអនឡាញសម្រាប់គ្រប់គ្រងអាជីវកម្ម។',
    summaryEn:
      'Enable access to the online services used to administer a business.',
    whoCanApplyKm: ['បុគ្គលដែលត្រូវការប្រើប្រាស់សេវាកម្មអនឡាញសម្រាប់គ្រប់គ្រងអាជីវកម្ម'],
    whoCanApplyEn: ['Any person who needs to use the online services to administer a business'],
    conditionsKm: ['ត្រូវមានអាសយដ្ឋានអ៊ីមែលដែលអាចទទួលការជូនដំណឹង', PLACEHOLDER_KM],
    conditionsEn: ['A working email address able to receive notifications', PLACEHOLDER_EN],
    requiredInformationKm: ['ព័ត៌មានអ្នកប្រើប្រាស់', 'អាសយដ្ឋានអ៊ីមែល', 'លេខទូរស័ព្ទទំនាក់ទំនង'],
    requiredInformationEn: ['User details', 'Email address', 'Contact telephone number'],
    requiredDocumentsKm: [PLACEHOLDER_KM],
    requiredDocumentsEn: [PLACEHOLDER_EN],
    stepsKm: [
      'បំពេញទម្រង់ចុះឈ្មោះអ្នកប្រើប្រាស់',
      'ផ្ទៀងផ្ទាត់អាសយដ្ឋានអ៊ីមែល',
      'ធ្វើឲ្យគណនីដំណើរការ',
      'ចូលប្រើប្រាស់សេវាកម្មអនឡាញ',
    ],
    stepsEn: [
      'Complete the new user registration form',
      'Verify the email address',
      'Activate the account',
      'Log in to the online services',
    ],
    whatHappensNextKm: ['អ្នកនឹងទទួលបានអ៊ីមែលអំពីការធ្វើឲ្យគណនីដំណើរការ'],
    whatHappensNextEn: ['You receive an email regarding account activation'],
    feeNoteKm: FEE_NOTE_KM,
    feeNoteEn: FEE_NOTE_EN,
    relatedFormIds: ['form-online-account'],
    relatedFaqIds: ['faq-new-user', 'faq-activate'],
    lastVerifiedAt: '2024-01-01',
  },
  {
    slug: 'reserve-business-name',
    icon: 'bookmark',
    group: 'registration',
    loginRequired: true,
    titleKm: 'បម្រុងទុកនាមករណ៍អាជីវកម្ម',
    titleEn: 'Reserve a Business Name',
    summaryKm:
      'បម្រុងទុកនាមករណ៍អាជីវកម្មជាភាសាខ្មែរ និងអង់គ្លេស មុនពេលបង្កើតអាជីវកម្មថ្មី ឬមុនពេលផ្លាស់ប្តូរឈ្មោះក្រុមហ៊ុន។',
    summaryEn:
      'Reserve a proposed Khmer and English business name before incorporation or a company-name change.',
    whoCanApplyKm: [
      'អ្នកដែលមានបំណងបង្កើតអាជីវកម្មថ្មី',
      'ក្រុមហ៊ុនដែលមានស្រាប់ដែលមានបំណងផ្លាស់ប្តូរឈ្មោះ',
    ],
    whoCanApplyEn: [
      'Applicants intending to establish a new business',
      'Existing companies intending to change their business name',
    ],
    conditionsKm: [
      'នាមករណ៍មិនត្រូវធ្វើឲ្យមានការភាន់ច្រឡំ បំភាន់ ឬប៉ះពាល់សីលធម៌',
      'នាមករណ៍ដែលបានអនុម័តមានសុពលភាពរយៈពេលបីខែ',
      'អាចសុំបន្តរយៈពេលបីខែបន្ថែមតាមនីតិវិធី និងការបង់ថ្លៃសេវាដែលពាក់ព័ន្ធ',
    ],
    conditionsEn: [
      'A name must not be confusing, misleading or offensive',
      'An approved name reservation remains valid for three months',
      'It may be extended for another three months through the applicable process and payment',
    ],
    requiredInformationKm: [
      'ប្រភេទអាជីវកម្ម ឬអង្គភាពដែលពាក់ព័ន្ធ',
      'នាមករណ៍ស្នើសុំជាភាសាខ្មែរ',
      'នាមករណ៍ស្នើសុំជាភាសាអង់គ្លេស',
    ],
    requiredInformationEn: [
      'The relevant business or entity type',
      'The proposed name in Khmer',
      'The proposed name in English',
    ],
    requiredDocumentsKm: ['ការបញ្ចូលឯកសារគាំទ្រអាចជាជម្រើស'],
    requiredDocumentsEn: ['Supporting-document upload may be optional'],
    stepsKm: [
      'ចូលប្រើប្រាស់គណនីរបស់អ្នក',
      'ជ្រើសរើសប្រភេទអាជីវកម្ម ឬអង្គភាព',
      'បញ្ចូលនាមករណ៍ជាភាសាខ្មែរ និងអង់គ្លេស',
      'បញ្ចូលឯកសារគាំទ្រ (ប្រសិនបើមាន)',
      'បង់ថ្លៃសេវាដែលពាក់ព័ន្ធ',
      'ដាក់ស្នើសម្រាប់ការពិនិត្យ',
    ],
    stepsEn: [
      'Log in to your account',
      'Select the relevant business or entity type',
      'Enter the proposed name in Khmer and English',
      'Upload supporting documents where applicable',
      'Pay the applicable fee',
      'Submit for review',
    ],
    whatHappensNextKm: [
      'អ្នកនឹងទទួលបានអ៊ីមែលអំពីលទ្ធផលនៃការស្នើសុំ',
      'នាមករណ៍ដែលបានអនុម័តអាចប្រើសម្រាប់ការចុះបញ្ជី ឬការផ្លាស់ប្តូរឈ្មោះ',
    ],
    whatHappensNextEn: [
      'You receive an email about the outcome of the request',
      'An approved name may be used for registration or a name change',
    ],
    feeNoteKm: FEE_NOTE_KM,
    feeNoteEn: FEE_NOTE_EN,
    relatedFormIds: ['form-name-authorisation', 'form-change-company-name'],
    relatedLawIds: ['prakas-company-naming'],
    relatedFaqIds: ['faq-reserve-name', 'faq-name-validity'],
    lastVerifiedAt: '2024-01-01',
  },
  {
    slug: 'register-business',
    icon: 'building',
    group: 'registration',
    loginRequired: true,
    titleKm: 'ចុះបញ្ជីអាជីវកម្មរបស់អ្នក',
    titleEn: 'Register Your Business',
    summaryKm: 'ចាប់ផ្តើម និងដាក់ស្នើពាក្យសុំចុះបញ្ជីពាណិជ្ជកម្មថ្មី។',
    summaryEn: 'Start and submit a new business-registration application.',
    whoCanApplyKm: ['អ្នកប្រើប្រាស់ដែលបានចុះឈ្មោះ និងមានគណនីដំណើរការ'],
    whoCanApplyEn: ['Registered users with an activated account'],
    conditionsKm: ['ត្រូវជ្រើសរើសប្រភេទអង្គភាព ឬសេវាកម្មចុះបញ្ជីដែលពាក់ព័ន្ធ', PLACEHOLDER_KM],
    conditionsEn: ['The relevant entity type or registration service must be selected', PLACEHOLDER_EN],
    requiredInformationKm: [
      'ព័ត៌មានអាជីវកម្ម',
      'អាសយដ្ឋាន',
      'ព័ត៌មានកម្មសិទ្ធិ និងភាគហុន',
      'ព័ត៌មានប្រធាន ឬអភិបាល',
      'សកម្មភាពអាជីវកម្ម',
    ],
    requiredInformationEn: [
      'Business information',
      'Address',
      'Ownership and shareholding information',
      'Director information',
      'Business activities',
    ],
    requiredDocumentsKm: ['ឯកសារដែលត្រូវការសម្រាប់ពាក្យស្នើសុំដែលបានជ្រើសរើស'],
    requiredDocumentsEn: ['Documents required for the selected application'],
    stepsKm: [
      'ចូលប្រើប្រាស់គណនីរបស់អ្នក',
      'ជ្រើសរើសសេវាកម្មចុះបញ្ជី',
      'បញ្ចូលនាមករណ៍ដែលបានបម្រុងទុក ឬស្នើសុំនាមករណ៍',
      'បំពេញពាក្យស្នើសុំ',
      'បញ្ចូលឯកសារគាំទ្រ',
      'បង់ថ្លៃសេវាដែលពាក់ព័ន្ធ',
      'ដាក់ស្នើសម្រាប់ការពិនិត្យផ្ទៃក្នុង',
    ],
    stepsEn: [
      'Log in to your account',
      'Select the registration service',
      'Enter the reserved or proposed business name',
      'Complete the application',
      'Upload supporting documents',
      'Pay the applicable fee',
      'Submit for internal review',
    ],
    whatHappensNextKm: [
      'ពាក្យស្នើសុំត្រូវបានផ្ញើទៅការពិនិត្យផ្ទៃក្នុង',
      'អ្នកនឹងទទួលបានអ៊ីមែលនៅពេលពាក្យត្រូវបានអនុម័ត ត្រឡប់មកវិញដើម្បីកែតម្រូវ ឬត្រូវបានបដិសេធ',
    ],
    whatHappensNextEn: [
      'The application is sent for internal review',
      'You receive an email when the application is approved, returned for correction, or rejected',
    ],
    feeNoteKm: FEE_NOTE_KM,
    feeNoteEn: FEE_NOTE_EN,
    relatedFormIds: ['form-enterprise-declaration', 'form-company-declaration', 'form-branch-declaration'],
    relatedLawIds: ['prakas-moc-public-services', 'prakas-brd-organization'],
    relatedFaqIds: ['faq-register-business', 'faq-application-result'],
    lastVerifiedAt: '2024-01-01',
  },
  {
    slug: 'search-the-register',
    icon: 'search',
    group: 'search',
    titleKm: 'ស្វែងរកក្នុងបញ្ជីពាណិជ្ជកម្ម',
    titleEn: 'Search the Register',
    summaryKm: 'ស្វែងរកអង្គភាព តួនាទី ឈ្មោះដែលបានបម្រុងទុក និងផ្ទៀងផ្ទាត់លេខកូដឯកសារ។',
    summaryEn: 'Search entities, roles, reserved names, and document verification codes.',
    whoCanApplyKm: ['សាធារណជនទាំងអស់'],
    whoCanApplyEn: ['Available to the public'],
    conditionsKm: ['មិនតម្រូវឲ្យចូលប្រើប្រាស់គណនី'],
    conditionsEn: ['No account login is required'],
    requiredInformationKm: ['ពាក្យគន្លឹះ ឬលេខចុះបញ្ជី'],
    requiredInformationEn: ['A keyword or registration number'],
    requiredDocumentsKm: ['មិនតម្រូវ'],
    requiredDocumentsEn: ['None'],
    stepsKm: ['ជ្រើសរើសប្រភេទស្វែងរក', 'បញ្ចូលពាក្យគន្លឹះ ឬលេខចុះបញ្ជី', 'ពិនិត្យលទ្ធផល'],
    stepsEn: ['Select the search type', 'Enter a keyword or registration number', 'Review the results'],
    whatHappensNextKm: ['លទ្ធផលបង្ហាញព័ត៌មានអង្គភាពដែលអាចផ្សព្វផ្សាយជាសាធារណៈ'],
    whatHappensNextEn: ['Results display publicly available entity information'],
    feeNoteKm: 'សេវាកម្មស្វែងរកជាសាធារណៈ។ ' + FEE_NOTE_KM,
    feeNoteEn: 'Public search service. ' + FEE_NOTE_EN,
    relatedFaqIds: ['faq-search-entity', 'faq-verify-document'],
    lastVerifiedAt: '2024-01-01',
  },
  {
    slug: 'change-business-details',
    icon: 'file-pen',
    group: 'maintenance',
    loginRequired: true,
    titleKm: 'កែប្រែព័ត៌មានអាជីវកម្ម',
    titleEn: 'Change Business Details',
    summaryKm: 'ដាក់ស្នើការកែប្រែព័ត៌មានសម្រាប់ក្រុមហ៊ុនដែលបានចុះបញ្ជី។',
    summaryEn: 'Submit changes for a registered company.',
    whoCanApplyKm: ['អ្នកប្រើប្រាស់ដែលមានសិទ្ធិគ្រប់គ្រងក្រុមហ៊ុនពាក់ព័ន្ធ'],
    whoCanApplyEn: ['Users holding the required authority over the company'],
    conditionsKm: [
      'ត្រូវចូលប្រើប្រាស់គណនី',
      'ត្រូវមានសិទ្ធិគ្រប់គ្រងក្រុមហ៊ុន',
      'ក្រុមហ៊ុនត្រូវបំពេញលក្ខខណ្ឌចុះបញ្ជីដែលពាក់ព័ន្ធ',
    ],
    conditionsEn: [
      'The user must be logged in',
      'The user must hold the required authority',
      'The company must meet the applicable registration conditions',
    ],
    requiredInformationKm: ['ព័ត៌មានកែប្រែដែលពាក់ព័ន្ធតាមប្រភេទការកែប្រែ'],
    requiredInformationEn: ['The amended information relevant to the type of change'],
    requiredDocumentsKm: ['បែបបទ និងឯកសារគាំទ្រតាមប្រភេទការកែប្រែ'],
    requiredDocumentsEn: ['The forms and supporting documents for the type of change'],
    stepsKm: [
      'ចូលប្រើប្រាស់គណនីរបស់អ្នក',
      'ជ្រើសរើសក្រុមហ៊ុន និងប្រភេទការកែប្រែ',
      'បំពេញព័ត៌មានកែប្រែ',
      'បញ្ចូលឯកសារគាំទ្រ',
      'បង់ថ្លៃសេវាដែលពាក់ព័ន្ធ',
      'ដាក់ស្នើសម្រាប់ការពិនិត្យ',
    ],
    stepsEn: [
      'Log in to your account',
      'Select the company and the type of change',
      'Complete the amended information',
      'Upload supporting documents',
      'Pay the applicable fee',
      'Submit for review',
    ],
    whatHappensNextKm: ['អ្នកនឹងទទួលបានអ៊ីមែលអំពីស្ថានភាពពាក្យស្នើសុំ'],
    whatHappensNextEn: ['You receive email notifications about the application status'],
    feeNoteKm: FEE_NOTE_KM,
    feeNoteEn: FEE_NOTE_EN,
    relatedFormIds: ['form-change-office', 'form-change-representative', 'form-increase-capital', 'form-transfer-shares'],
    relatedLawIds: ['prakas-company-changes'],
    relatedFaqIds: ['faq-update-company'],
    lastVerifiedAt: '2024-01-01',
  },
  {
    slug: 'annual-declaration',
    icon: 'calendar-check',
    group: 'maintenance',
    loginRequired: true,
    titleKm: 'ការប្រកាសព័ត៌មានប្រចាំឆ្នាំ',
    titleEn: 'Annual Declaration',
    summaryKm: 'ចូលប្រើប្រាស់ព័ត៌មាន និងសេវាកម្មសម្រាប់ការដាក់ប្រកាសព័ត៌មានប្រចាំឆ្នាំ។',
    summaryEn: 'Access annual-declaration filing information and services.',
    whoCanApplyKm: ['ក្រុមហ៊ុន និងសហគ្រាសដែលបានចុះបញ្ជី'],
    whoCanApplyEn: ['Registered companies and enterprises'],
    conditionsKm: ['ត្រូវចូលប្រើប្រាស់គណនី និងមានសិទ្ធិគ្រប់គ្រងក្រុមហ៊ុន', PLACEHOLDER_KM],
    conditionsEn: ['Login and company authority are required', PLACEHOLDER_EN],
    requiredInformationKm: ['ព័ត៌មានប្រកាសប្រចាំឆ្នាំតាមទម្រង់ផ្លូវការ'],
    requiredInformationEn: ['The annual declaration information required by the official form'],
    requiredDocumentsKm: ['បែបបទប្រកាសព័ត៌មានប្រចាំឆ្នាំ'],
    requiredDocumentsEn: ['The annual declaration form'],
    stepsKm: [
      'ចូលប្រើប្រាស់គណនីរបស់អ្នក',
      'ជ្រើសរើសក្រុមហ៊ុន',
      'បំពេញព័ត៌មានប្រកាសប្រចាំឆ្នាំ',
      'បង់ថ្លៃសេវាដែលពាក់ព័ន្ធ',
      'ដាក់ស្នើ',
    ],
    stepsEn: [
      'Log in to your account',
      'Select the company',
      'Complete the annual declaration information',
      'Pay the applicable fee',
      'Submit',
    ],
    whatHappensNextKm: ['អ្នកនឹងទទួលបានអ៊ីមែលបញ្ជាក់ការដាក់ស្នើ'],
    whatHappensNextEn: ['You receive an email confirming the submission'],
    feeNoteKm: FEE_NOTE_KM,
    feeNoteEn: FEE_NOTE_EN,
    relatedFormIds: ['form-annual-declaration'],
    relatedLawIds: ['prakas-annual-declaration'],
    relatedFaqIds: ['faq-annual-declaration'],
    lastVerifiedAt: '2024-01-01',
  },
  {
    slug: 'certificates-and-extracts',
    icon: 'award',
    group: 'maintenance',
    loginRequired: true,
    titleKm: 'វិញ្ញាបនបត្រ និងសម្រង់',
    titleEn: 'Certificates and Extracts',
    summaryKm: 'ស្នើសុំវិញ្ញាបនបត្រ និងសម្រង់ក្រុមហ៊ុនដែលមានផ្តល់ជូន។',
    summaryEn: 'Request available company certificates and extracts.',
    whoCanApplyKm: ['អ្នកប្រើប្រាស់ដែលមានសិទ្ធិគ្រប់គ្រងក្រុមហ៊ុនពាក់ព័ន្ធ'],
    whoCanApplyEn: ['Users holding the required authority over the company'],
    conditionsKm: ['ត្រូវចូលប្រើប្រាស់គណនី', PLACEHOLDER_KM],
    conditionsEn: ['Login is required', PLACEHOLDER_EN],
    requiredInformationKm: ['ព័ត៌មានក្រុមហ៊ុន និងប្រភេទឯកសារដែលស្នើសុំ'],
    requiredInformationEn: ['Company information and the type of document requested'],
    requiredDocumentsKm: [PLACEHOLDER_KM],
    requiredDocumentsEn: [PLACEHOLDER_EN],
    stepsKm: ['ចូលប្រើប្រាស់គណនី', 'ជ្រើសរើសក្រុមហ៊ុន និងឯកសារ', 'បង់ថ្លៃសេវាដែលពាក់ព័ន្ធ', 'ទាញយកឯកសារអេឡិចត្រូនិក'],
    stepsEn: ['Log in', 'Select the company and document', 'Pay the applicable fee', 'Download the electronic document'],
    whatHappensNextKm: [
      'វិញ្ញាបនបត្រអេឡិចត្រូនិកអាចមានត្រាអេឡិចត្រូនិក លេខកូដ QR និងហត្ថលេខា',
    ],
    whatHappensNextEn: [
      'Electronic certificates may contain an electronic stamp, QR code and signature',
    ],
    feeNoteKm: FEE_NOTE_KM,
    feeNoteEn: FEE_NOTE_EN,
    relatedFaqIds: ['faq-certificate'],
    lastVerifiedAt: '2024-01-01',
  },
  {
    slug: 'company-authority',
    icon: 'key-round',
    group: 'account',
    loginRequired: true,
    titleKm: 'ដំណើរការគណនី ឬសិទ្ធិគ្រប់គ្រងក្រុមហ៊ុន',
    titleEn: 'Activate Account or Company Authority',
    summaryKm:
      'ធ្វើឲ្យគណនីអ្នកប្រើប្រាស់ដំណើរការ ឬស្នើសុំសិទ្ធិគ្រប់គ្រងក្រុមហ៊ុនដែលមានស្រាប់។',
    summaryEn:
      'Activate a user account or request authority to maintain an existing company.',
    whoCanApplyKm: ['អ្នកប្រើប្រាស់ដែលបានចុះឈ្មោះ'],
    whoCanApplyEn: ['Registered users'],
    conditionsKm: [PLACEHOLDER_KM],
    conditionsEn: [PLACEHOLDER_EN],
    requiredInformationKm: ['ព័ត៌មានគណនី និងព័ត៌មានក្រុមហ៊ុនពាក់ព័ន្ធ'],
    requiredInformationEn: ['Account information and the relevant company information'],
    requiredDocumentsKm: ['ពាក្យស្នើសុំសិទ្ធិគ្រប់គ្រងក្រុមហ៊ុន'],
    requiredDocumentsEn: ['The company authority request form'],
    stepsKm: ['ចូលប្រើប្រាស់គណនី', 'ជ្រើសរើសសេវាកម្មពាក់ព័ន្ធ', 'បញ្ចូលឯកសារគាំទ្រ', 'ដាក់ស្នើសម្រាប់ការពិនិត្យ'],
    stepsEn: ['Log in', 'Select the relevant service', 'Upload supporting documents', 'Submit for review'],
    whatHappensNextKm: ['អ្នកនឹងទទួលបានអ៊ីមែលអំពីលទ្ធផល'],
    whatHappensNextEn: ['You receive an email about the outcome'],
    feeNoteKm: FEE_NOTE_KM,
    feeNoteEn: FEE_NOTE_EN,
    relatedFormIds: ['form-company-authority', 'form-online-account'],
    relatedFaqIds: ['faq-activate'],
    lastVerifiedAt: '2024-01-01',
  },
]

export function getService(slug: string) {
  return services.find((service) => service.slug === slug)
}

/** Maintenance services listed on the current website for registered companies. */
export const maintenanceServices: MaintenanceService[] = [
  {
    slug: 'change-company-name',
    titleKm: 'ផ្លាស់ប្តូរឈ្មោះក្រុមហ៊ុន',
    titleEn: 'Change Company Name',
    descriptionKm: 'ដាក់ស្នើការផ្លាស់ប្តូរឈ្មោះក្រុមហ៊ុនដែលបានចុះបញ្ជី។',
    descriptionEn: 'Submit a change to the registered company name.',
  },
  {
    slug: 'change-articles-of-incorporation',
    titleKm: 'ផ្លាស់ប្តូរលក្ខន្តិកៈ',
    titleEn: 'Change Articles of Incorporation',
    descriptionKm: 'ដាក់ស្នើលក្ខន្តិកៈដែលបានធ្វើបច្ចុប្បន្នភាព។',
    descriptionEn: 'File updated articles of incorporation.',
  },
  {
    slug: 'change-registered-office-address',
    titleKm: 'ផ្លាស់ប្តូរអាសយដ្ឋានទីស្នាក់ការចុះបញ្ជី',
    titleEn: 'Change Registered Office Address',
    descriptionKm: 'ធ្វើបច្ចុប្បន្នភាពអាសយដ្ឋានទីស្នាក់ការចុះបញ្ជី។',
    descriptionEn: 'Update the registered office address.',
  },
  {
    slug: 'appoint-or-cease-directors',
    titleKm: 'តែងតាំង ឬបញ្ចប់តួនាទីអភិបាល',
    titleEn: 'Appoint or Cease Directors',
    descriptionKm: 'ធ្វើបច្ចុប្បន្នភាពសមាសភាពក្រុមប្រឹក្សាភិបាល ឬអភិបាល។',
    descriptionEn: 'Update the board or director composition.',
  },
  {
    slug: 'update-shareholdings',
    titleKm: 'ធ្វើបច្ចុប្បន្នភាពការកាន់កាប់ភាគហុន',
    titleEn: 'Update Shareholdings',
    descriptionKm: 'ធ្វើបច្ចុប្បន្នភាពព័ត៌មានភាគហុនិក។',
    descriptionEn: 'Update shareholder information.',
  },
  {
    slug: 'update-share-capital',
    titleKm: 'ធ្វើបច្ចុប្បន្នភាពដើមទុន',
    titleEn: 'Update Share Capital',
    descriptionKm: 'ដាក់ស្នើការបង្កើន ឬកែប្រែដើមទុន។',
    descriptionEn: 'Submit an increase or amendment of share capital.',
  },
  {
    slug: 'transfer-shares',
    titleKm: 'ផ្ទេរភាគហុន',
    titleEn: 'Transfer Shares',
    descriptionKm: 'ដាក់ស្នើការផ្ទេរភាគហុន។',
    descriptionEn: 'Submit a transfer of shares.',
  },
  {
    slug: 'change-business-activities',
    titleKm: 'បន្ថែម ឬដកសកម្មភាពអាជីវកម្ម',
    titleEn: 'Change Business Activities',
    descriptionKm: 'បន្ថែម ឬដកសកម្មភាពអាជីវកម្មដែលបានចុះបញ្ជី។',
    descriptionEn: 'Add or remove registered business activities.',
  },
  {
    slug: 'request-certificates-or-extracts',
    titleKm: 'ស្នើសុំវិញ្ញាបនបត្រ ឬសម្រង់',
    titleEn: 'Request Certificates or Extracts',
    descriptionKm: 'ស្នើសុំឯកសារក្រុមហ៊ុនដែលមានផ្តល់ជូន។',
    descriptionEn: 'Request available company documents.',
  },
  {
    slug: 'file-an-annual-declaration',
    titleKm: 'ដាក់ប្រកាសព័ត៌មានប្រចាំឆ្នាំ',
    titleEn: 'File an Annual Declaration',
    descriptionKm: 'ដាក់ស្នើប្រកាសព័ត៌មានប្រចាំឆ្នាំ។',
    descriptionEn: 'Submit the annual declaration.',
  },
]
